In [46]:
import numpy as np 
import cv2
import imutils


In [47]:
cap = cv2.VideoCapture("/home/roar/Desktop/ROARLaneDetection/training_1000.MOV")
cap.isOpened()

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d98fbeddc0] Referenced QT chapter track not found


True

In [48]:
while True:
    ret,frame = cap.read()
    if not ret:
        break
    #frame = imutils.resize(frame,width = 960)
    seed = (1079, 960)

    box = (200, 200)
    x = (seed[0] - box[0] - box[1], seed[0])
    y = (seed[1] - box[1], seed[1] + box[1])

    mean = np.mean(frame[x[0]:x[1], y[0]:y[1], :], axis = (0,1))
    std = np.std(frame[x[0]:x[1], y[0]:y[1], :], axis = (0,1))
    scale = 2.5
    scale_std = std * scale
    
    print(mean, '/n',std)

    frame[seed[0], seed[1]] = mean

    cv2.floodFill(frame, None, seedPoint=seed, newVal=(0, 0, 255), loDiff=tuple(scale_std), upDiff=tuple(scale_std), flags= cv2.FLOODFILL_FIXED_RANGE)
    #cv2.circle(frame, seed, 2, (0, 255, 0), cv2.FILLED, cv2.LINE_AA);

    cv2.imshow('image',frame)
    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        cv2.destroyAllWindows()
        break

[157.01363125 159.930925   163.0903625 ] /n [43.0776409  42.67949907 41.9260563 ]
[156.8000375 159.630325  162.7286   ] /n [43.78288467 43.41500565 42.68197503]
[156.7317     159.54986875 162.6479375 ] /n [43.78000117 43.41276757 42.68525436]
[156.7780625  159.19573125 162.47854375] /n [44.34589264 44.07430681 43.2847033 ]
[156.81965625 159.05000625 162.39563125] /n [44.6654021  44.45655892 43.6554784 ]
[156.19553125 158.71994375 161.45886875] /n [45.69903608 45.42433805 44.76023803]
[156.1516375  158.5132875  161.32820625] /n [46.24215264 46.01130145 45.31428968]
[155.98139375 158.3170375  161.14465   ] /n [46.25082253 46.03852666 45.3352756 ]
[155.43404375 157.8648125  160.5342875 ] /n [46.68767704 46.43389238 45.7813383 ]
[155.51598125 157.58404375 160.2977625 ] /n [47.26961386 47.10152969 46.44061907]
[155.23546875 157.3480375  159.95821875] /n [47.34784616 47.17223662 46.53216775]
[155.1638125  157.36214375 159.8219375 ] /n [47.57259561 47.37001697 46.7689056 ]
[155.1597375  157.0